{"uuid": "76b97c77-b492-423d-a7bf-f1ed55045ac4", "children": ["85b8e7ea-f6c3-4d41-afd8-22c2a920f96d", "8ba8cd61-c867-4f88-8068-938affc5df1a", "df8808b1-aef4-4340-be03-0276a5746ef1"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20303ms.\n\n", "trace": "  File \"c:\\program files\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\program files\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\monal\\PycharmProjects\\AppiumFrameworks\\AppiumFrameWork\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.getDriverMethod()\n  File \"C:\\Users\\monal\\PycharmProjects\\AppiumFrameworks\\AppiumFrameWork\\base\\DriverClass.py\", line 13, in getDriverMethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"c:\\program files\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 155, in __init__\n    proxy\n  File \"c:\\program files\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\program files\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"c:\\program files\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614241208583, "stop": 1614241229295}], "start": 1614241208583, "stop": 1614241229938}